version: "3.3"
services:      
  webserver:
    image: nginx:alpine
    restart: always
    depends_on:
      - wordpress
    ports:
      - "8080:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: mariadb:10.8.2
    restart: always
    env_file: .env
    environment:
      - MARIADB_DATABASE=wordpress
    volumes: 
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    image: wordpress:php7.4-fpm-alpine
    restart: always
    depends_on: 
      - db
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MARIADB_USER
      - WORDPRESS_DB_PASSWORD=$MARIADB_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - "8000:80"

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge  
